---

- name: "install required software security updates"
  yum:
    security: "yes"
    lock_timeout: 60
    state: "latest"

- name: Disable SELinux
  selinux:
    state: disabled

- name: "include Docker installation tasks"
  include_tasks: "docker.yml"