name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          templateFile: 'ami.json'

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          templateFile: 'ami.json'
          workingDir: '0.AMI'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
